// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Investments = sequelize.define('investments', {
    name: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'Investments',
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Investments.associate = (models) => {
    Investments.belongsTo(models.brokers, {
      foreignKey: {
        name: 'brokerIdKey',
        field: 'BrokerId',
      },
      as: 'broker',
    });
    Investments.hasMany(models.transactions, {
      foreignKey: {
        name: 'investmentIdKey',
        field: 'InvestmentId',
      },
      as: 'investmentTransactions',
    });
    Investments.hasMany(models.balanceUpdates, {
      foreignKey: {
        name: 'investmentIdKey',
        field: 'InvestmentId',
      },
      as: 'investmentBalanceUpdates',
    });
  };

  return Investments;
};
